* Why Static
** Scalability
WordPress sites cache to get the same effect.
** Security
No php, no database, no queries, no xss
** Defaulting Dynamic
Most websites are now dynamically generated in real-time, with caching, complexity is massive before you even start!
** Static is simple
Static sites do not crash, they are easier to debug because a complex component of many sites (server-side) is no longer present.
** Static-Dynamic
Making site static, but rapidly generating static, seem dynamic with all the benefits of static.
** Javascript
Things that used to be done on the server-side (dynamically) can now be performed client side with JavaScript APIs. 
* Jekyll
Tool for generating static websites. 
** Why now?
***  Standard way of generating static websites, better then the custom script-per site approach.
*** GitHub has adopted it for website hosting, pushing popularity + adoption
Makes sense, one of the founders of GitHub built it. Tom-Preston-Werner (built Gravatar too!)
*** Combines a lot of other useful techs
Jekyll is the generator, the techs involved are things like
**** YAML
**** Markdown/Textile / HTML
**** Sass / CSS
**** Liquid / HTML
Very loose in variable use, doesnt error much... Can operate on missing things, nothing happens. good!
*** But you don't /need/ to use anything beyond YAML
** What is Jekyll
*** Magic implicit configuration
http://pchiusano.github.io/2014-05-20/jekyll-vs-hakyll.html
*** Ruby
*** Generates a site based on /filesystem structure/ and /front matter/
*** Helpful tools besides generation like:
**** --serve
**** --watch
serve now watches by default
** Jekyll Technologies
*** Ruby
Don't need to know much about Ruby
*** YAML
Format for how you give information to Jekyll for processing
*** Liquid
Templating language, looks a lot like all the others, lots of people use it, you know mostly Shopify and GitHub.
*** Sass
*** Markdown
** /Front Matter/ & /Filenames/
** Filesystem layout
** Configuration file
** Your Data Files
Pages / Posts / Etc
** Your Top-Level Pages
** Your Posts
** Custom Types (Collections)
** Your Layouts
** Sugar
*** Pagenator!
*** Data files
* Jekyll Integrations
** Jekyll/S3
https://github.com/laurilehmijoki/s3_website
** GitHub Pages

*** Special branch for projects
gh-pages : git checkout --orphan gh-pages
***
  Extra data available
  https://help.github.com/articles/repository-metadata-on-github-pages
* Jekyll in Real Life
** Obama 2012 donation site
http://kylerush.net/blog/meet-the-obama-campaigns-250-million-fundraising-platform/
s3/cdn/js API for dynamic stuff
 

** Healthcare.gov
Remember that scene? Partially served statically now
https://www.healthcare.gov/
